name: Feature Request
description: Suggest an idea for PyImgAno
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving PyImgAno!
        Please describe your feature request in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would like to use this feature
      render: python
      placeholder: |
        from pyimgano import models
        detector = models.create_model("new_model")
        # Example usage

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - New Model
        - API Enhancement
        - Performance Improvement
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: This would help users who...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I am willing to contribute to this feature (optional)
          required: false
