from __future__ import annotations

from pyimgano.exporting.adapters import register_builtin_export_adapters
from pyimgano.exporting.exporters.composite import (
    CompositeArtifactExportResult,
    CompositeExportError,
    export_composite,
)
from pyimgano.exporting.exporters.native import NativeExportError, export_native
from pyimgano.exporting.exporters.single_graph import (
    GraphArtifactExportResult,
    SingleGraphExportError,
    export_single_graph,
)
from pyimgano.exporting.protocols import (
    CheckpointRoundTripProtocol,
    ComponentExportProtocol,
    ExportAdapterProtocol,
    GraphExportProtocol,
)
from pyimgano.exporting.registry import (
    EXPORT_ADAPTER_REGISTRY,
    ExportAdapterRegistrationError,
    ExportAdapterRegistry,
    build_export_support_table,
    get_export_adapter,
    get_export_capability,
    register_export_adapter,
)
from pyimgano.exporting.state_codec import (
    FITTED_STATE_FORMAT,
    FITTED_STATE_VERSION,
    STATE_CODEC_REGISTRY,
    FittedStateInfo,
    MappingStateCodec,
    StateCodecError,
    StateCodecRegistry,
    StateField,
    get_state_codec,
    get_state_codec_for_model,
    inspect_checkpoint_contract,
    inspect_fitted_state,
    load_fitted_state,
    register_state_codec,
    save_fitted_state,
)
from pyimgano.exporting.types import (
    ArtifactFormat,
    CapabilityAvailability,
    CheckpointCompleteness,
    CheckpointContract,
    ComponentExportSpec,
    ExportCapability,
    ExportLayout,
    ExportStatus,
    ExportTargetKind,
    GraphExportSpec,
    NativeExportContext,
    NativeExportResult,
    ProbeSpec,
    SerializationKind,
)

register_builtin_export_adapters()

__all__ = [
    "ArtifactFormat",
    "CapabilityAvailability",
    "CheckpointCompleteness",
    "CheckpointContract",
    "CheckpointRoundTripProtocol",
    "CompositeArtifactExportResult",
    "CompositeExportError",
    "ComponentExportProtocol",
    "ComponentExportSpec",
    "EXPORT_ADAPTER_REGISTRY",
    "ExportAdapterProtocol",
    "ExportAdapterRegistrationError",
    "ExportAdapterRegistry",
    "ExportCapability",
    "ExportLayout",
    "ExportStatus",
    "ExportTargetKind",
    "FITTED_STATE_FORMAT",
    "FITTED_STATE_VERSION",
    "FittedStateInfo",
    "GraphExportProtocol",
    "GraphExportSpec",
    "GraphArtifactExportResult",
    "MappingStateCodec",
    "NativeExportContext",
    "NativeExportError",
    "NativeExportResult",
    "ProbeSpec",
    "STATE_CODEC_REGISTRY",
    "SerializationKind",
    "StateCodecError",
    "StateCodecRegistry",
    "StateField",
    "SingleGraphExportError",
    "build_export_support_table",
    "get_export_adapter",
    "get_export_capability",
    "get_state_codec",
    "get_state_codec_for_model",
    "inspect_checkpoint_contract",
    "inspect_fitted_state",
    "load_fitted_state",
    "register_export_adapter",
    "register_state_codec",
    "save_fitted_state",
    "export_native",
    "export_composite",
    "export_single_graph",
]
