#!/usr/bin/env python3
"""Generate a markdown tag history from git tags + CHANGELOG.

This repo already maintains curated release notes in `CHANGELOG.md`, but the git
tags are named with a `v` prefix (e.g. `v0.6.33`). This script generates a tag
oriented view that:

- Uses CHANGELOG sections for semantic version tags (`vX.Y.Z`)
- Falls back to commit subjects for non-semver tags (e.g. milestones)

Usage
-----
    python tools/generate_tag_history.py

Outputs
-------
    docs/TAG_HISTORY.md
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG_PATH = ROOT / "CHANGELOG.md"
OUT_PATH = ROOT / "docs" / "TAG_HISTORY.md"

SEMVER_TAG_RE = re.compile(r"^v(?P<ver>\d+\.\d+\.\d+)$")
# Example: "## [0.6.33] - 2026-03-05"
CHANGELOG_HEADER_RE = re.compile(
    r"^## \[(?P<ver>\d+\.\d+\.\d+)\] - (?P<date>.+?)\s*$"
)


@dataclass(frozen=True)
class ChangelogSection:
    version: str
    date: str
    body_lines: tuple[str, ...]


def _sh(*args: str) -> str:
    return subprocess.check_output(args, cwd=str(ROOT), text=True).strip()


def _git_tags_by_date() -> list[str]:
    # `creatordate` works for both annotated tags and lightweight tags.
    out = _sh("git", "tag", "--list", "--sort=creatordate")
    tags = [t.strip() for t in out.splitlines() if t.strip()]
    return tags


def _git_commit_date(ref: str) -> str:
    # Use commit date (YYYY-MM-DD) for stability.
    return _sh("git", "log", "-1", "--format=%cs", ref)


def _git_log_subjects(prev_ref: str, ref: str, *, limit: int = 30) -> list[str]:
    # Keep it stable and readable: short sha + subject line.
    rng = f"{prev_ref}..{ref}"
    out = _sh("git", "log", "--format=%h %s", "--no-decorate", f"-n{limit}", rng)
    lines = [ln.rstrip() for ln in out.splitlines() if ln.strip()]
    return lines


def _load_changelog_sections() -> dict[str, ChangelogSection]:
    text = CHANGELOG_PATH.read_text(encoding="utf-8")
    lines = text.splitlines()

    sections: dict[str, ChangelogSection] = {}
    current_ver: str | None = None
    current_date: str | None = None
    current_body: list[str] = []

    def flush() -> None:
        nonlocal current_ver, current_date, current_body
        if current_ver is None or current_date is None:
            return
        sections[current_ver] = ChangelogSection(
            version=current_ver,
            date=current_date,
            body_lines=tuple(current_body),
        )
        current_ver = None
        current_date = None
        current_body = []

    for line in lines:
        if line.startswith("## Release Notes Guidelines"):
            # Everything below is generic guidance, not a tag/version section.
            flush()
            break

        m = CHANGELOG_HEADER_RE.match(line)
        if m:
            flush()
            current_ver = m.group("ver")
            current_date = m.group("date")
            current_body = []
            continue

        if current_ver is not None:
            current_body.append(line)

    flush()
    return sections


def _render_tag_section_from_changelog(tag: str, section: ChangelogSection) -> list[str]:
    lines: list[str] = []
    lines.append(f"## {tag} - {section.date}")
    lines.append("")
    # Keep the body as-is, but trim leading blank lines.
    body = list(section.body_lines)
    while body and body[0].strip() == "":
        body.pop(0)
    lines.extend(body)
    lines.append("")
    return lines


def _render_tag_section_from_commits(tag: str, *, date: str, prev_tag: str | None) -> list[str]:
    lines: list[str] = []
    lines.append(f"## {tag} - {date}")
    lines.append("")
    if prev_tag is None:
        lines.append("- Initial tag (no previous tag to diff).")
        lines.append("")
        return lines

    subjects = _git_log_subjects(prev_tag, tag, limit=50)
    lines.append("### Commits")
    if not subjects:
        lines.append("- (No commits; tag points at previous tag commit)")
        lines.append("")
        return lines

    for subj in subjects:
        lines.append(f"- {subj}")
    lines.append("")
    return lines


def main() -> int:
    tags = _git_tags_by_date()
    changelog_sections = _load_changelog_sections()

    prev_by_tag: dict[str, str | None] = {}
    prev: str | None = None
    for t in tags:
        prev_by_tag[t] = prev
        prev = t

    out_lines: list[str] = []
    out_lines.append("# Tag History")
    out_lines.append("")
    out_lines.append("This file is generated by `tools/generate_tag_history.py`.")
    out_lines.append("")
    out_lines.append("- For `vX.Y.Z` tags: content is sourced from `CHANGELOG.md` section `[X.Y.Z]`.")
    out_lines.append("- For non-semver tags: content is derived from commit subjects between tags.")
    out_lines.append("")
    out_lines.append("Regenerate:")
    out_lines.append("")
    out_lines.append("```bash")
    out_lines.append("python tools/generate_tag_history.py")
    out_lines.append("```")
    out_lines.append("")

    # Newest first (like most changelogs).
    for tag in reversed(tags):
        m = SEMVER_TAG_RE.match(tag)
        if m:
            ver = m.group("ver")
            section = changelog_sections.get(ver)
            if section is not None:
                out_lines.extend(_render_tag_section_from_changelog(tag, section))
                continue

        date = _git_commit_date(tag)
        out_lines.extend(
            _render_tag_section_from_commits(
                tag,
                date=date,
                prev_tag=prev_by_tag.get(tag),
            )
        )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(out_lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
